=== BRGM/daobs/harvesters/csw-harvester/src/main/resources/daobsHarvesterConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://daobs.org"
           xmlns:ogc="http://www.opengis.net/ogc"
           xmlns:daobs="http://daobs.org">
  <xs:element name="harvesters">
    <xs:annotation>
      <xs:documentation>
        A set of harvester configuration.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="daobs:harvester"/>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="harvester-url-key">
      <xs:selector xpath="daobs:harvester"/>
      <xs:field xpath="daobs:url"/>
    </xs:key>
  </xs:element>
  <xs:element name="harvester">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="daobs:uuid"/>
        <xs:element ref="daobs:territory"/>
        <xs:element ref="daobs:folder"/>
        <xs:element ref="daobs:name"/>
        <xs:element ref="daobs:url"/>
        <xs:element minOccurs="0" ref="daobs:filter"/>
        <xs:element minOccurs="0" ref="daobs:nbOfRecordsPerPage">
          <xs:annotation>
            <xs:documentation>
              If not provided, the harvester config parameter is used.
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="daobs:pointOfTruthURLPattern"/>
        <xs:element ref="daobs:serviceMetadata"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="uuid" type="xs:string">
    <xs:annotation>
      <xs:documentation>
        Unique identifier for the harvester. A good practice
        is to use here the identifier of the metadata
        record corresponding to the discovery service.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="territory" type="xs:NCName">
    <xs:annotation>
      <xs:documentation>
        A "territory" identifier which allows to group records
        from different harvesters in the same group. It could be
        a country code, a region code. Usually, this key is
        something that can't be extracted from the metadata records.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="folder" type="xs:string">
    <xs:annotation>
      <xs:documentation>
        A folder name which is used to store harvested records.
        The CSW GetRecords responses are saved in that folder with
        a file name based on the following pattern:

        {{YYYYMMDD}}-{{pageNumberStartingAt0}}.xml

        It could be the same value as territory if there is no
        need to make distinction between harvesters.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="name" type="xs:string">
    <xs:annotation>
      <xs:documentation>
        The name of the harvested node.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="url" type="xs:anyURI">
    <xs:annotation>
      <xs:documentation>
        The URL of the CSW server without parameters like SERVICE,
        REQUEST, VERSION.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="filter" type="xs:anyType">
    <xs:annotation>
      <xs:documentation>
        An extra filter to be applied to the GetRecords query
        to select a subset of records in the harvested node.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="nbOfRecordsPerPage" type="xs:int">
    <xs:annotation>
      <xs:documentation>
        The number of records per page to be harvested.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="pointOfTruthURLPattern" type="xs:anyURI">
    <xs:annotation>
      <xs:documentation>
        URL pattern which could provide an hyperlink to a webpage
        pointing to the metadata record in HTML or XML or other formats.
        The URL MUST contains a flag {{uuid}} to be substituted
        by the record identifier.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="serviceMetadata" type="xs:anyURI">
    <xs:annotation>
      <xs:documentation>
        A URL pointing to the metadata record of the service
        endpoint.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>

=== BRGM/daobs/web/src/main/webapp/WEB-INF/datadir/harvester/config-harvesters.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2014-2016 European Environment Agency
  ~
  ~ Licensed under the EUPL, Version 1.1 or – as soon
  ~ they will be approved by the European Commission -
  ~ subsequent versions of the EUPL (the "Licence");
  ~ You may not use this work except in compliance
  ~ with the Licence.
  ~ You may obtain a copy of the Licence at:
  ~
  ~ https://joinup.ec.europa.eu/community/eupl/og_page/eupl
  ~
  ~ Unless required by applicable law or agreed to in
  ~ writing, software distributed under the Licence is
  ~ distributed on an "AS IS" basis,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
  ~ either express or implied.
  ~ See the Licence for the specific language governing
  ~ permissions and limitations under the Licence.
  -->
<daobs:harvesters xmlns:daobs="http://daobs.org"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="../../daobsHarvesterConfig.xsd">
  <daobs:harvester>
    <daobs:uuid>3f25ac7a-35fa-4a38-ae8b-68f05c8967aa</daobs:uuid>
    <daobs:territory>FR</daobs:territory>
    <daobs:folder>FR</daobs:folder>
    <daobs:name>Geocatalogue Catalogue Server INSPIRE (BRGM)</daobs:name>
    <daobs:url>http://www.geocatalogue.fr/api-public/inspire/servicesRest</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>1412</daobs:uuid>
    <daobs:territory>GEONORMANDIE</daobs:territory>
    <daobs:folder>GEONORMANDIE</daobs:folder>
    <daobs:name>GeoNormandie</daobs:name>
    <daobs:url>http://catalogue.geonormandie.fr/geonetwork/srv/fre/csw-local?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>607</daobs:uuid>
    <daobs:territory>SEXTANT</daobs:territory>
    <daobs:folder>SEXTANT</daobs:folder>
    <daobs:name>Sextant</daobs:name>
    <daobs:url>http://sextant.ifremer.fr/geonetwork/srv/fre/csw-GEOCATALOGUE?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>601</daobs:uuid>
    <daobs:territory>DREALPACA</daobs:territory>
    <daobs:folder>DREALPACA</daobs:folder>
    <daobs:name>DREAL PACA</daobs:name>
    <daobs:url>http://metadata.carmencarto.fr/geosource/25/fre/csw?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>1301</daobs:uuid>
    <daobs:territory>GEOBOURGOGNE</daobs:territory>
    <daobs:folder>GEOBOURGOGNE</daobs:folder>
    <daobs:name>GéoBourgogne</daobs:name>
    <daobs:url>http://www.geobourgogne.fr/geonetwork/srv/fre/csw-local?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>51520</daobs:uuid>
    <daobs:territory>CARGOS</daobs:territory>
    <daobs:folder>CARGOS</daobs:folder>
    <daobs:name>CArGOS</daobs:name>
    <daobs:url>http://cargos.huma-num.fr/geosource/srv/fre/csw?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>450</daobs:uuid>
    <daobs:territory>CARMEN</daobs:territory>
    <daobs:folder>CARMEN</daobs:folder>
    <daobs:name>carmen</daobs:name>
    <daobs:url>http://metadata.carmencarto.fr/geosource/61/fre/csw?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>1411</daobs:uuid>
    <daobs:territory>52</daobs:territory>
    <daobs:folder>52</daobs:folder>
    <daobs:name>52</daobs:name>
    <daobs:url>http://www.mongeosource.fr/geosource/geosource/fre/csw?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>1151</daobs:uuid>
    <daobs:territory>GEORHONEALPES</daobs:territory>
    <daobs:folder>GEORHONEALPES</daobs:folder>
    <daobs:name>GEORHONEALPES</daobs:name>
    <daobs:url>http://www.georhonealpes.fr/geonetwork/srv/fre/csw-RAIN?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>51466</daobs:uuid>
    <daobs:territory>CATALOGUEANAEE</daobs:territory>
    <daobs:folder>CATALOGUEANAEE</daobs:folder>
    <daobs:name>catalogue anaee</daobs:name>
    <daobs:url>http://w3.avignon.inra.fr/geonetwork_anaee/srv/eng/csw?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>1253</daobs:uuid>
    <daobs:territory>SIGLOIRE</daobs:territory>
    <daobs:folder>SIGLOIRE</daobs:folder>
    <daobs:name>Sigloire</daobs:name>
    <daobs:url>http://catalogue.sigloire.fr/geonetwork/srv/fre/csw-sigloire?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>457</daobs:uuid>
    <daobs:territory>SANDRE</daobs:territory>
    <daobs:folder>SANDRE</daobs:folder>
    <daobs:name>SANDRE</daobs:name>
    <daobs:url>http://services.sandre.eaufrance.fr/geonetwork_CSW/srv/en/csw?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>51421</daobs:uuid>
    <daobs:territory>DREALPICARDIE</daobs:territory>
    <daobs:folder>DREALPICARDIE</daobs:folder>
    <daobs:name>DREAL Picardie</daobs:name>
    <daobs:url>http://metadata.carmencarto.fr/geosource/27/fre/csw?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>51490</daobs:uuid>
    <daobs:territory>GEOPLATEFORME17</daobs:territory>
    <daobs:folder>GEOPLATEFORME17</daobs:folder>
    <daobs:name>Géoplateforme17</daobs:name>
    <daobs:url>http://test.geoplateforme17.fr/proxy/geonetwork-prod?CONSTRAINT_LANGUAGE_VERSION=1.1.0</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>455</daobs:uuid>
    <daobs:territory>CARMEN(MNHN)</daobs:territory>
    <daobs:folder>CARMEN(MNHN)</daobs:folder>
    <daobs:name>CARMEN (MNHN)</daobs:name>
    <daobs:url>http://metadata.carmencarto.fr:80/geosource/119/eng/csw?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>51450</daobs:uuid>
    <daobs:territory>ERDF</daobs:territory>
    <daobs:folder>ERDF</daobs:folder>
    <daobs:name>ERDF</daobs:name>
    <daobs:url>http://www.mongeosource.fr/geosource/1187/fre/csw?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>1354</daobs:uuid>
    <daobs:territory>PEGASEPOITOU-CHARENTES</daobs:territory>
    <daobs:folder>PEGASEPOITOU-CHARENTES</daobs:folder>
    <daobs:name>Pegase Poitou-Charentes</daobs:name>
    <daobs:url>http://www.pegase-poitou-charentes.fr/geonetwork/srv/fre/csw?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>615</daobs:uuid>
    <daobs:territory>GEOPAL</daobs:territory>
    <daobs:folder>GEOPAL</daobs:folder>
    <daobs:name>Geopal</daobs:name>
    <daobs:url>http://www.geopal.org/geonetwork/srv/fre/csw-local?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>51516</daobs:uuid>
    <daobs:territory>SHOM</daobs:territory>
    <daobs:folder>SHOM</daobs:folder>
    <daobs:name>shom</daobs:name>
    <daobs:url>http://services.data.shom.fr/csw/ISOAP</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>401</daobs:uuid>
    <daobs:territory>ADELIE</daobs:territory>
    <daobs:folder>ADELIE</daobs:folder>
    <daobs:name>ADELIE</daobs:name>
    <daobs:url>http://adelie.application.developpement-durable.gouv.fr/minicsw.do?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>51469</daobs:uuid>
    <daobs:territory>TIGEO</daobs:territory>
    <daobs:folder>TIGEO</daobs:folder>
    <daobs:name>TIGeo</daobs:name>
    <daobs:url>http://www.tigeo.fr/proxy/geonetwork-cat?CONSTRAINT_LANGUAGE_VERSION=1.1.0</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>51431</daobs:uuid>
    <daobs:territory>ONF</daobs:territory>
    <daobs:folder>ONF</daobs:folder>
    <daobs:name>ONF</daobs:name>
    <daobs:url>http://www.mongeosource.fr/geosource/Admin_ONF/fre/csw?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>51413</daobs:uuid>
    <daobs:territory>AGENCEDELEAUARTOIS-PICARDIE</daobs:territory>
    <daobs:folder>AGENCEDELEAUARTOIS-PICARDIE</daobs:folder>
    <daobs:name>Agence de l'eau Artois-Picardie</daobs:name>
    <daobs:url>http://www.mongeosource.fr/geosource/admin_52/fre/csw?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>454</daobs:uuid>
    <daobs:territory>IFN</daobs:territory>
    <daobs:folder>IFN</daobs:folder>
    <daobs:name>IFN</daobs:name>
    <daobs:url>http://geosource.ifn.fr/geonetwork/srv/fre/csw?</daobs:url>
    <daobs:nbOfRecordsPerPage>200</daobs:nbOfRecordsPerPage>
  </daobs:harvester>
  <daobs:harvester>
    <daobs:uuid>51455</daobs:uuid>
    <daobs:territory>CONSEILDEPARTEMENTALPAS-DE-CALAIS</daobs:territory>
    <daobs:folder>CONSEILDEPARTEMENTALPAS-DE-CALAIS</daobs:folder>
    <daobs:name>Conseil Départemental Pas-de-Calais</daobs:name>
    <daobs:url>http://api.isogeo.com/services/csw/s/3f5cb018fe4e48dcac7f6039acd01962/c/44ae43fb7d4c40da99ed8eb9bf5d2833/ZKyGZvBoeonP1vIzCeAAwJqDc4HifEMRC2fH4sTg4dRh6cy4A5G9JC/GetRecords</daobs:url>
